name: "Onzo Energy Monitor"
description: "Read Onzo energy monitor data"
version: "1.0.41"
usb: true
slug: "onzo_energy_monitor"
init: false
homeassistant_api: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
privileged:
    - "SYS_ADMIN"
    - "DAC_READ_SEARCH"
    - "SYS_RAWIO"
options:
    vid: "0x04d8"
    pid: "0x003f"
schema:
   vid: str
   pid: str
